version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    env_file:
      - .env
    volumes:
      - ${PWD}/data/postgres:/data/postgres
    ports:
      - '5432:5432'

  voucher-pool:
    build:
      context: .
    container_name: 'voucher-poolapi'
    image: 'voucher-poolapi:latest'  
    ports:
      - '3000:3000'
    environment:
      - .env
    depends_on:
      - postgres
